---
title: "Modul 12 - Finale Prüfungsleistung - Jannis Vollmer - MMI23"
output: html_notebook
---

# Einleitung
tbd

# Datensatz
Der originale Datensatz wurde ursprünglich von der University of Michigan erstellt. Diese Arbeit untersucht ein Subset des eigentlichen, originalen Datensatzes. Die Daten wurden erfasst, um relevante Einblicke in die Gesundheit von Patientinnen und Patienten über 50 Jahren, sowie das Gesundheitssystem in den Vereinigten Staaten von Amerika zu untersuchen. Dabei werden verschiedenste Kategorien, wie z.B. Versicherungsstatus, Schlafstörungen oder Medikation betrachtet.

Jede Zeile im Datensatz repräsentiert einen Umfrageteilnehmer. Insgesamt gibt es 714. Der Datensatz enthält sensible Daten, darunter Informationen zu Rasse/Ethnizität, Geschlecht und Alter. Für die Untermenge des ursprünglichen NPHA-Datensatzes wurden 14 Merkmale ausgewählt, die sich auf Gesundheit und Schlaf beziehen, um eine Vorhersageaufgabe zu ermöglichen. Alle Umfrageteilnehmer mit fehlenden Antworten auf eines der ausgewählten Merkmale wurden entfernt, sodass der Datensatz keine fehlenden Werte enthält.

## Feature-Beschreibung
Es gibt insgesamt 14 Features, die alle katgorische Werte enthalten. 

### Target-Feature
Das Target-Feature in dieser Arbeit ist "Number_of_Doctors_Visited" und enthält die Anzahl der verschiedenen Ärzte, die ein Patient bzw. eine Patientin in einem Jahr gesehen hat:
1: 0-1 Ärzte
2: 2-3 Ärzte
3: 4 oder mehr Ärzte

Fehlende Werte gibt es nicht.

### Andere Features
Es gibt 13 weitere Features im Datensatz, die zur Untersuchung herangezogen werden können. Die folgende Tabelle zeigt die Definition der Werte

| Kategorie                              | Wert | Beschreibung                        |
|----------------------------------------|------|-------------------------------------|
| **Age**                              | 1    | 50-64                               |
|                                        | 2    | 65-80                               |
| **Physical_Health**             | -1   | Abgelehnt                           |
|                                        | 1    | Ausgezeichnet                       |
|                                        | 2    | Sehr gut                            |
|                                        | 3    | Gut                                 |
|                                        | 4    | Befriedigend                        |
|                                        | 5    | Schlecht                            |
| **Mental_Health**                | -1   | Abgelehnt                           |
|                                        | 1    | Ausgezeichnet                       |
|                                        | 2    | Sehr gut                            |
|                                        | 3    | Gut                                 |
|                                        | 4    | Befriedigend                        |
|                                        | 5    | Schlecht                            |
| **Dental_Health**                     | -1   | Abgelehnt                           |
|                                        | 1    | Ausgezeichnet                       |
|                                        | 2    | Sehr gut                            |
|                                        | 3    | Gut                                 |
|                                        | 4    | Befriedigend                        |
|                                        | 5    | Schlecht                            |
| **Employment**                      | -1   | Abgelehnt                           |
|                                        | 1    | Vollzeit beschäftigt                |
|                                        | 2    | Teilzeit beschäftigt                |
|                                        | 3    | Im Ruhestand                        |
|                                        | 4    | Zurzeit nicht beschäftigt           |
| **Stress_Keeps_Patient_from_Sleeping**         | 0    | Nein                                |
|                                        | 1    | Ja                                  |
| **Medication_Keeps_Patient_from_Sleeping**    | 0    | Nein                                |
|                                        | 1    | Ja                                  |
| **Pain_Keeps_Patient_from_Sleeping**      | 0    | Nein                                |
|                                        | 1    | Ja                                  |
| **Bathroom_Needs_Keeps_Patient_from_Sleeping** | 0    | Nein                                |
|                                        | 1    | Ja                                  |
| **Uknown_Keeps_Patient_from_Sleeping** | 0 | Nein                                |
|                                        | 1    | Ja                                  |
| **Trouble_Sleeping**                     | 0    | Nein                                |
|                                        | 1    | Ja                                  |
| **Prescription_Sleep_Medication**         | -1   | Abgelehnt                           |
|                                        | 1    | Regelmäßige Nutzung                 |
|                                        | 2    | Gelegentliche Nutzung               |
|                                        | 3    | Keine Nutzung                       |
| **Race**                              | -2   | Nicht gefragt                       |
|                                        | -1   | Abgelehnt                           |
|                                        | 1    | Weiß, nicht-hispanisch              |
|                                        | 2    | Schwarz, nicht-hispanisch           |
|                                        | 3    | Andere, nicht-hispanisch            |
|                                        | 4    | Hispanisch                          |
|                                        | 5    | Zwei oder mehr Rassen, nicht-hispanisch |
| **Gender**                         | -2   | Nicht gefragt                       |
|                                        | -1   | Abgelehnt                           |
|                                        | 1    | Männlich                            |
|                                        | 2    | Weiblich                            |

Keiner dieser Features hat fehlende Werte. Diese wurden bereits im Vorwege entfernt.

# Forschungsfrage
Der vorliegende Datensatz sowie die darin beschriebenen Features sollen dazu genutzt werden, folgende Forschungsfrage zu beantworten: Ist es möglich, die Anzahl der Arztbesuche pro Jahr anhand der anderen Features vorherzusagen? 

Dabei wird untersucht, ob Variablen wie Gesundheit, Schlafqualität, Zahnpflege, verschreibungspflichtige Medikamente, Krankenversicherung und weitere relevante Faktoren dazu beitragen können, die Häufigkeit der Arztbesuche einer Person im Verlauf eines Jahres vorherzusagen. Ziel dieser Untersuchung ist es, ein besseres Verständnis dafür zu gewinnen, wie verschiedene gesundheitliche und soziodemografische Faktoren miteinander verknüpft sind und wie sie die Inanspruchnahme medizinischer Dienstleistungen beeinflussen.

# Beantwortung und Diskussion der Forschungsfrage
## Preprocessing
### z-tranformation
### principal component analysis
### plotting
### Zusammenfassung

## Supervised Learning
### Random Forest

```{r}
#testcodechunk
```

# Quellen
[1] Datensatz "National Poll on Healthy Aging": University of Michigan, United States, abrufbar unter https://archive.ics.uci.edu/dataset/936/national+poll+on+healthy+aging+(npha), zuletzt abgerufen am 20.06.2024.