---
title: "supervised2"
author: "Jannis Vollmer"
date: "2024-05-22"
output: html_document
---

```{r}
    require(caret)
    require(foreign)
```

# Task 4.3

## Supervised Learning - Regression and hyperparameter tuning

### Load data

```{r}
  data(BloodBrain)
  head(bbbDescr)
  
  X <- bbbDescr
  y <- logBBB
```

### Divide dataset into training and test data set
Creating a seperate test data set to get a realistic estimate of the performance after hyperparameter tuning.
```{r}
  inTrain <- createDataPartition(y, p=0.75, list = FALSE)
  
  X_train <- X[inTrain,]
  y_train <- y[inTrain]
  x_test <- X[inTrain,]
  y_test <- y[-inTrain]
```

### Train the model
#### Define a tuning grid for a random forest classifier by varying parameter mtry from 2 to 8

```{r}
  featVar <- apply(X_train,2,var)
```


```{r}
  trControl <- trainControl(method="cv", number=10)
  model_rf <- train(X_train, y_train, method="rf", trainControl=trControl)
  model_rf
```

```{r}
  vi <- varImp(model_rf)
  plot(vi)
```