---
title: "supervised"
author: "Jannis Vollmer"
date: "2024-05-03"
output: html_document
---

# Installation of needed packages
```{r}
  install.packages("caret")
  require(caret)
```

# Regression

```{r}
  heart_data <- read.csv("../data sets/heartdata.csv", row.names = 1)
  cor(heart_data$biking, heart_data$smoking)
  plot(heart_data$biking, heart_data$smoking)
  hist(heart_data$biking)
```

```{r}
  plot(heartdisease ~ biking, data=heart_data)
  plot(heartdisease ~ smoking, data=heart_data)
```

## Linear model
```{r}
  hd_lm <- lm(heartdisease ~ biking + smoking, data=heart_data)
  summary(hd_lm)
```

### plotting of linear model
```{r}
  plot(hd_lm)
  # plotting placeholder (Step 5 in tutorial) -> to do
```

## Training the model
```{r}
  fitControl <- trainControl(method= "cv", number = 10)
  lmFit <- train(heartdisease ~ ., data=heart_data, method="lm", trControl=fitControl, preProc=c("center", "scale"))
  lmFit
```

# Classification

```{r}
  library(foreign)
  diabetes_data <- read.arff("../data sets/diabetes.arff")
  diaFit <- glm(class ~ ., data = diabetes_data, family="binomial")
  summary(diaFit)
  
  #add plotting
```

```{r}
  glmFit <- train(class ~ ., data=diabetes_data, method="glm", trControl=fitControl, preProc=c("center", "scale"))
  glmFit
```
